apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-lite
spec:
  nodeName: node01
  containers:
  - name: tensorflow-lite-12
    image: altair4357/2023paper:tensorflow-lite
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    resources:
      requests:
        cpu: 4000m
        memory: 15750Mi
      limits:
        cpu: 4000m
        memory: 15750Mi
