apiVersion: v1
kind: Pod
metadata:
  name: custom-scheduler
spec:
  containers:
  - name: custom-scheduler
    image: altair4357/custom_scheduler:0.24
    imagePullPolicy: Always
  serviceAccountName: custom-scheduler


