apiVersion: v1
kind: Pod
metadata:
  name: blender
spec:
  nodeName: node01
  containers:
  - name: blender-6
    image: altair4357/2023paper:blender
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    resources:
      requests:
        cpu: 7000m
        memory: 15750Mi
      limits:
        cpu: 7000m
        memory: 15750Mi
