apiVersion: v1
kind: Pod
metadata:
  name: build-apache
spec:
  nodeName: node01
  containers:
  - name: build-apache-7
    image: altair4357/2023paper:build-apache
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    resources:
      requests:
        cpu: 4000m
        memory: 1500Mi
      limits:
        cpu: 4000m
        memory: 1500Mi
