apiVersion: v1
kind: Pod
metadata:
  name: c-ray
spec:
  nodeName: node01
  containers:
  - name: c-ray-8
    image: altair4357/2023paper:c-ray
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    resources:
      requests:
        cpu: 4000m
        memory: 30000Mi
      limits:
        cpu: 4000m
        memory: 30000Mi
